services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - both-network

  backend:
    build: ./dummy-backend
    ports:
      - "3001:3000"
    networks:
      - both-network

networks:
  both-network:
    driver: bridge